import type { AiTool } from "@/types/ai-tool";

export const aiTools: AiTool[] = [
  {
    id: "cursor",
    name: "Cursor",
    slug: "cursor",
    logo: "",
    logoUrl: "",
    category: "Coding Assistant",
    tagline: "AI-first editor for everyday development work.",
    description:
      "Useful for code navigation, multi-file edits, refactors, and fast iteration inside a familiar editor workflow.",
    shortDescription:
      "AI-first code editor for faster builds and focused iteration.",
    fullDescription:
      "Cursor is a strong fit for developers who want AI close to the codebase, especially for refactors, navigation, and multi-file implementation work.",
    websiteUrl: "https://cursor.com",
    affiliateUrl: "",
    pricingType: "freemium",
    startingPrice: "$0",
    pricingSummary: "Free tier with paid plans",
    bestFor: ["Code editing", "Refactors", "Project navigation"],
    pros: ["Excellent editor fit", "Strong codebase context", "Fast iteration"],
    cons: ["Requires careful review", "Can feel noisy without discipline"],
    easeOfUseScore: 8,
    pricingValueScore: 8,
    featuresScore: 9,
    developerUsefulnessScore: 9,
    overallScore: 9,
    status: "published",
    accentClass: "bg-teal-500",
    isFeatured: true,
  },
  {
    id: "claude",
    name: "Claude",
    slug: "claude",
    logo: "",
    logoUrl: "",
    category: "AI Assistant",
    tagline: "Long-context assistant for planning, writing, and debugging.",
    description:
      "Best used for reasoning-heavy work, turning messy notes into plans, reviewing decisions, and drafting technical content.",
    shortDescription:
      "Long-context assistant for planning, debugging, and technical writing.",
    fullDescription:
      "Claude is useful when a task needs careful reasoning, long notes, code review, or structured technical writing before implementation.",
    websiteUrl: "https://claude.ai",
    affiliateUrl: "",
    pricingType: "freemium",
    startingPrice: "$0",
    pricingSummary: "Free tier with paid plans",
    bestFor: ["Planning", "Debugging", "Technical writing"],
    pros: ["Strong reasoning", "Good long-context behavior", "Clear writing"],
    cons: ["Not a full IDE", "Output still needs verification"],
    easeOfUseScore: 9,
    pricingValueScore: 8,
    featuresScore: 8,
    developerUsefulnessScore: 9,
    overallScore: 9,
    status: "published",
    accentClass: "bg-amber-500",
    isFeatured: true,
  },
  {
    id: "perplexity",
    name: "Perplexity",
    slug: "perplexity",
    logo: "",
    logoUrl: "",
    category: "Research",
    tagline: "Search-backed research for technical discovery.",
    description:
      "Helpful for quick source-backed research, tool discovery, documentation hunting, and comparison prep.",
    shortDescription: "Search-backed answers for quick technical discovery.",
    fullDescription:
      "Perplexity is useful when a workflow begins with uncertain information, source checking, or quick discovery across docs and web results.",
    websiteUrl: "https://www.perplexity.ai",
    affiliateUrl: "",
    pricingType: "freemium",
    startingPrice: "$0",
    pricingSummary: "Free tier with paid plans",
    bestFor: ["Research", "Source checking", "Discovery"],
    pros: ["Fast research", "Useful citations", "Good discovery workflow"],
    cons: ["Sources still need checking", "Not a replacement for docs"],
    easeOfUseScore: 9,
    pricingValueScore: 8,
    featuresScore: 8,
    developerUsefulnessScore: 8,
    overallScore: 8,
    status: "published",
    accentClass: "bg-blue-500",
    isFeatured: true,
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    slug: "github-copilot",
    logo: "",
    logoUrl: "",
    category: "Coding Assistant",
    tagline: "Code completion and assistant features inside developer tools.",
    description:
      "A practical baseline for comparing AI coding assistance across editors, pull requests, and daily implementation work.",
    shortDescription: "AI coding assistant integrated across GitHub workflows.",
    fullDescription:
      "GitHub Copilot is a useful baseline for editor assistance, completions, and teams already working deeply inside GitHub.",
    websiteUrl: "https://github.com/features/copilot",
    affiliateUrl: "",
    pricingType: "paid",
    startingPrice: "$10/month",
    pricingSummary: "Paid plans with limited free access",
    bestFor: ["Code completion", "Editor assistance", "GitHub workflows"],
    pros: ["Mature ecosystem", "Strong editor support", "Team-friendly"],
    cons: ["Less workflow-specific than agentic editors", "Value depends on stack"],
    easeOfUseScore: 8,
    pricingValueScore: 7,
    featuresScore: 8,
    developerUsefulnessScore: 8,
    overallScore: 8,
    status: "published",
    accentClass: "bg-violet-500",
    isFeatured: false,
  },
  {
    id: "chatgpt",
    name: "ChatGPT",
    slug: "chatgpt",
    logo: "",
    logoUrl: "",
    category: "AI Assistant",
    tagline: "General AI workspace for coding, writing, and analysis.",
    description:
      "Useful across brainstorming, code explanation, learning support, lightweight automation, and content drafting.",
    shortDescription: "General AI workspace for coding, writing, and analysis.",
    fullDescription:
      "ChatGPT is flexible for builders who need one broad assistant for explanation, ideation, code help, learning, and content drafting.",
    websiteUrl: "https://chatgpt.com",
    affiliateUrl: "",
    pricingType: "freemium",
    startingPrice: "$0",
    pricingSummary: "Free tier with paid plans",
    bestFor: ["General assistance", "Learning", "Drafting"],
    pros: ["Broad use cases", "Strong ecosystem", "Good learning support"],
    cons: ["Needs focused prompts", "Can be too general for specific workflows"],
    easeOfUseScore: 9,
    pricingValueScore: 8,
    featuresScore: 9,
    developerUsefulnessScore: 8,
    overallScore: 8,
    status: "published",
    accentClass: "bg-emerald-500",
    isFeatured: false,
  },
  {
    id: "notion-ai",
    name: "Notion AI",
    slug: "notion-ai",
    logo: "",
    logoUrl: "",
    category: "Knowledge Workspace",
    tagline: "AI features inside notes, docs, and team knowledge bases.",
    description:
      "Useful for summarizing notes, drafting documentation, organizing research, and improving lightweight operations docs.",
    shortDescription: "AI inside notes, docs, and team knowledge bases.",
    fullDescription:
      "Notion AI works best for teams already organizing docs and operations inside Notion, especially for summaries and documentation drafts.",
    websiteUrl: "https://www.notion.so/product/ai",
    affiliateUrl: "",
    pricingType: "paid",
    startingPrice: "Paid add-on",
    pricingSummary: "Paid add-on and bundled plans",
    bestFor: ["Notes", "Documentation", "Knowledge management"],
    pros: ["Convenient in docs", "Good for summaries", "Useful team context"],
    cons: ["Best only inside Notion", "Not developer-specific"],
    easeOfUseScore: 8,
    pricingValueScore: 7,
    featuresScore: 7,
    developerUsefulnessScore: 6,
    overallScore: 7,
    status: "published",
    accentClass: "bg-rose-500",
    isFeatured: false,
  },
];

export const featuredAiTools = aiTools.filter((tool) => tool.isFeatured);

export const aiToolCategories = Array.from(
  new Set(aiTools.map((tool) => tool.category)),
).sort();
